#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 28, 2019 10:44:33 AM GMT  platform: Darwin

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import GUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = MainWindow (root)
    GUI_support.init(root, top)
    root.mainloop()

w = None
def create_MainWindow(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = MainWindow (w)
    GUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MainWindow():
    global w
    w.destroy()
    w = None

class MainWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family Arial -size 48 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("1742x1050+50+23")
        top.minsize(72, 15)
        top.maxsize(1742, 1075)
        top.resizable(0, 0)
        top.title("AutoRead")
        top.configure(background="#ff00cc")

        self.Master_Container = tk.Frame(top)
        self.Master_Container.place(relx=0.006, rely=0.01, relheight=0.976
                , relwidth=0.985)
        self.Master_Container.configure(relief='groove')
        self.Master_Container.configure(borderwidth="2")
        self.Master_Container.configure(relief="groove")
        self.Master_Container.configure(background="#00ffcc")

        self.MCT = tk.LabelFrame(self.Master_Container)
        self.MCT.place(relx=0.006, rely=0.01, relheight=0.844, relwidth=0.985)
        self.MCT.configure(relief='ridge')
        self.MCT.configure(foreground="black")
        self.MCT.configure(relief="ridge")
        self.MCT.configure(text='''Drama Theatre - TAIT PI MCCs''')
        self.MCT.configure(background="#d9d9d9")

        self.Label1 = tk.Label(self.MCT)
        self.Label1.place(relx=0.006, rely=0.023, height=61, width=440
                , bordermode='ignore')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Axis 1 @ 00000mm''')

        self.Label1_3 = tk.Label(self.MCT)
        self.Label1_3.place(relx=0.006, rely=0.092, height=61, width=132
                , bordermode='ignore')
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Label''')

        self.Label1_4 = tk.Label(self.MCT)
        self.Label1_4.place(relx=0.006, rely=0.162, height=61, width=132
                , bordermode='ignore')
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Label''')

        self.Label1_5 = tk.Label(self.MCT)
        self.Label1_5.place(relx=0.006, rely=0.231, height=61, width=132
                , bordermode='ignore')
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(background="#d9d9d9")
        self.Label1_5.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(text='''Label''')

        self.Label1_6 = tk.Label(self.MCT)
        self.Label1_6.place(relx=0.006, rely=0.301, height=61, width=132
                , bordermode='ignore')
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(background="#d9d9d9")
        self.Label1_6.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_6.configure(foreground="#000000")
        self.Label1_6.configure(highlightbackground="#d9d9d9")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(text='''Label''')

        self.Label1_7 = tk.Label(self.MCT)
        self.Label1_7.place(relx=0.006, rely=0.37, height=61, width=132
                , bordermode='ignore')
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''Label''')

        self.Label1_8 = tk.Label(self.MCT)
        self.Label1_8.place(relx=0.006, rely=0.439, height=61, width=132
                , bordermode='ignore')
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(text='''Label''')

        self.Label1_9 = tk.Label(self.MCT)
        self.Label1_9.place(relx=0.006, rely=0.509, height=61, width=132
                , bordermode='ignore')
        self.Label1_9.configure(activebackground="#f9f9f9")
        self.Label1_9.configure(activeforeground="black")
        self.Label1_9.configure(background="#d9d9d9")
        self.Label1_9.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_9.configure(foreground="#000000")
        self.Label1_9.configure(highlightbackground="#d9d9d9")
        self.Label1_9.configure(highlightcolor="black")
        self.Label1_9.configure(text='''Label''')

        self.Label1_9 = tk.Label(self.MCT)
        self.Label1_9.place(relx=0.006, rely=0.578, height=61, width=132
                , bordermode='ignore')
        self.Label1_9.configure(activebackground="#f9f9f9")
        self.Label1_9.configure(activeforeground="black")
        self.Label1_9.configure(background="#d9d9d9")
        self.Label1_9.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_9.configure(foreground="#000000")
        self.Label1_9.configure(highlightbackground="#d9d9d9")
        self.Label1_9.configure(highlightcolor="black")
        self.Label1_9.configure(text='''Label''')

        self.Label1_10 = tk.Label(self.MCT)
        self.Label1_10.place(relx=0.006, rely=0.647, height=61, width=132
                , bordermode='ignore')
        self.Label1_10.configure(activebackground="#f9f9f9")
        self.Label1_10.configure(activeforeground="black")
        self.Label1_10.configure(background="#d9d9d9")
        self.Label1_10.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_10.configure(foreground="#000000")
        self.Label1_10.configure(highlightbackground="#d9d9d9")
        self.Label1_10.configure(highlightcolor="black")
        self.Label1_10.configure(text='''Label''')

        self.Label1_11 = tk.Label(self.MCT)
        self.Label1_11.place(relx=0.006, rely=0.717, height=61, width=132
                , bordermode='ignore')
        self.Label1_11.configure(activebackground="#f9f9f9")
        self.Label1_11.configure(activeforeground="black")
        self.Label1_11.configure(background="#d9d9d9")
        self.Label1_11.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_11.configure(foreground="#000000")
        self.Label1_11.configure(highlightbackground="#d9d9d9")
        self.Label1_11.configure(highlightcolor="black")
        self.Label1_11.configure(text='''Label''')

        self.Label1_12 = tk.Label(self.MCT)
        self.Label1_12.place(relx=0.006, rely=0.786, height=61, width=132
                , bordermode='ignore')
        self.Label1_12.configure(activebackground="#f9f9f9")
        self.Label1_12.configure(activeforeground="black")
        self.Label1_12.configure(background="#d9d9d9")
        self.Label1_12.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_12.configure(foreground="#000000")
        self.Label1_12.configure(highlightbackground="#d9d9d9")
        self.Label1_12.configure(highlightcolor="black")
        self.Label1_12.configure(text='''Label''')

        self.Label1_13 = tk.Label(self.MCT)
        self.Label1_13.place(relx=0.006, rely=0.855, height=61, width=132
                , bordermode='ignore')
        self.Label1_13.configure(activebackground="#f9f9f9")
        self.Label1_13.configure(activeforeground="black")
        self.Label1_13.configure(background="#d9d9d9")
        self.Label1_13.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_13.configure(foreground="#000000")
        self.Label1_13.configure(highlightbackground="#d9d9d9")
        self.Label1_13.configure(highlightcolor="black")
        self.Label1_13.configure(text='''Label''')

        self.Label1_14 = tk.Label(self.MCT)
        self.Label1_14.place(relx=0.006, rely=0.925, height=61, width=132
                , bordermode='ignore')
        self.Label1_14.configure(activebackground="#f9f9f9")
        self.Label1_14.configure(activeforeground="black")
        self.Label1_14.configure(background="#d9d9d9")
        self.Label1_14.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_14.configure(foreground="#000000")
        self.Label1_14.configure(highlightbackground="#d9d9d9")
        self.Label1_14.configure(highlightcolor="black")
        self.Label1_14.configure(text='''Label''')

        self.Label1_15 = tk.Label(self.MCT)
        self.Label1_15.place(relx=0.308, rely=0.023, height=61, width=132
                , bordermode='ignore')
        self.Label1_15.configure(activebackground="#f9f9f9")
        self.Label1_15.configure(activeforeground="black")
        self.Label1_15.configure(background="#d9d9d9")
        self.Label1_15.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_15.configure(foreground="#000000")
        self.Label1_15.configure(highlightbackground="#d9d9d9")
        self.Label1_15.configure(highlightcolor="black")
        self.Label1_15.configure(text='''Label''')

        self.Label1_16 = tk.Label(self.MCT)
        self.Label1_16.place(relx=0.243, rely=0.092, height=61, width=132
                , bordermode='ignore')
        self.Label1_16.configure(activebackground="#f9f9f9")
        self.Label1_16.configure(activeforeground="black")
        self.Label1_16.configure(background="#d9d9d9")
        self.Label1_16.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_16.configure(foreground="#000000")
        self.Label1_16.configure(highlightbackground="#d9d9d9")
        self.Label1_16.configure(highlightcolor="black")
        self.Label1_16.configure(text='''Label''')

        self.Label1_17 = tk.Label(self.MCT)
        self.Label1_17.place(relx=0.243, rely=0.162, height=61, width=132
                , bordermode='ignore')
        self.Label1_17.configure(activebackground="#f9f9f9")
        self.Label1_17.configure(activeforeground="black")
        self.Label1_17.configure(background="#d9d9d9")
        self.Label1_17.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_17.configure(foreground="#000000")
        self.Label1_17.configure(highlightbackground="#d9d9d9")
        self.Label1_17.configure(highlightcolor="black")
        self.Label1_17.configure(text='''Label''')

        self.Label1_18 = tk.Label(self.MCT)
        self.Label1_18.place(relx=0.243, rely=0.231, height=61, width=132
                , bordermode='ignore')
        self.Label1_18.configure(activebackground="#f9f9f9")
        self.Label1_18.configure(activeforeground="black")
        self.Label1_18.configure(background="#00ff00")
        self.Label1_18.configure(font="-family {Arial} -size 48 -weight bold")
        self.Label1_18.configure(foreground="#000000")
        self.Label1_18.configure(highlightbackground="#d9d9d9")
        self.Label1_18.configure(highlightcolor="black")
        self.Label1_18.configure(text='''Label''')

        self.Labelframe_Node2 = tk.LabelFrame(self.MCT)
        self.Labelframe_Node2.place(relx=0.497, rely=0.023, relheight=0.954
                , relwidth=0.314, bordermode='ignore')
        self.Labelframe_Node2.configure(relief='groove')
        self.Labelframe_Node2.configure(foreground="black")
        self.Labelframe_Node2.configure(text='''MCC 2''')
        self.Labelframe_Node2.configure(background="#d9d9d9")
        self.Labelframe_Node2.configure(highlightbackground="#d9d9d9")
        self.Labelframe_Node2.configure(highlightcolor="black")

        self.Label3 = tk.Label(self.Labelframe_Node2)
        self.Label3.place(relx=0.038, rely=0.048, height=22, width=213
                , bordermode='ignore')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(justify='left')
        self.Label3.configure(text='''Axis 2''')

        self.Label3_30 = tk.Label(self.Labelframe_Node2)
        self.Label3_30.place(relx=0.038, rely=0.097, height=22, width=39
                , bordermode='ignore')
        self.Label3_30.configure(activebackground="#f9f9f9")
        self.Label3_30.configure(activeforeground="black")
        self.Label3_30.configure(background="#d9d9d9")
        self.Label3_30.configure(foreground="#000000")
        self.Label3_30.configure(highlightbackground="#d9d9d9")
        self.Label3_30.configure(highlightcolor="black")
        self.Label3_30.configure(text='''Axis 4''')

        self.Label3_31 = tk.Label(self.Labelframe_Node2)
        self.Label3_31.place(relx=0.038, rely=0.145, height=22, width=39
                , bordermode='ignore')
        self.Label3_31.configure(activebackground="#f9f9f9")
        self.Label3_31.configure(activeforeground="black")
        self.Label3_31.configure(background="#d9d9d9")
        self.Label3_31.configure(foreground="#000000")
        self.Label3_31.configure(highlightbackground="#d9d9d9")
        self.Label3_31.configure(highlightcolor="black")
        self.Label3_31.configure(text='''Axis 6''')

        self.Label3_32 = tk.Label(self.Labelframe_Node2)
        self.Label3_32.place(relx=0.038, rely=0.194, height=22, width=39
                , bordermode='ignore')
        self.Label3_32.configure(activebackground="#f9f9f9")
        self.Label3_32.configure(activeforeground="black")
        self.Label3_32.configure(background="#d9d9d9")
        self.Label3_32.configure(foreground="#000000")
        self.Label3_32.configure(highlightbackground="#d9d9d9")
        self.Label3_32.configure(highlightcolor="black")
        self.Label3_32.configure(text='''Axis 8''')

        self.Label3_33 = tk.Label(self.Labelframe_Node2)
        self.Label3_33.place(relx=0.038, rely=0.242, height=22, width=49
                , bordermode='ignore')
        self.Label3_33.configure(activebackground="#f9f9f9")
        self.Label3_33.configure(activeforeground="black")
        self.Label3_33.configure(background="#d9d9d9")
        self.Label3_33.configure(foreground="#000000")
        self.Label3_33.configure(highlightbackground="#d9d9d9")
        self.Label3_33.configure(highlightcolor="black")
        self.Label3_33.configure(justify='left')
        self.Label3_33.configure(text='''Axis 10''')

        self.Label3_34 = tk.Label(self.Labelframe_Node2)
        self.Label3_34.place(relx=0.038, rely=0.291, height=22, width=39
                , bordermode='ignore')
        self.Label3_34.configure(activebackground="#f9f9f9")
        self.Label3_34.configure(activeforeground="black")
        self.Label3_34.configure(background="#d9d9d9")
        self.Label3_34.configure(foreground="#000000")
        self.Label3_34.configure(highlightbackground="#d9d9d9")
        self.Label3_34.configure(highlightcolor="black")
        self.Label3_34.configure(text='''Axis 12''')

        self.Label3_35 = tk.Label(self.Labelframe_Node2)
        self.Label3_35.place(relx=0.038, rely=0.339, height=22, width=39
                , bordermode='ignore')
        self.Label3_35.configure(activebackground="#f9f9f9")
        self.Label3_35.configure(activeforeground="black")
        self.Label3_35.configure(background="#d9d9d9")
        self.Label3_35.configure(foreground="#000000")
        self.Label3_35.configure(highlightbackground="#d9d9d9")
        self.Label3_35.configure(highlightcolor="black")
        self.Label3_35.configure(text='''Label''')

        self.Label3_36 = tk.Label(self.Labelframe_Node2)
        self.Label3_36.place(relx=0.038, rely=0.388, height=22, width=39
                , bordermode='ignore')
        self.Label3_36.configure(activebackground="#f9f9f9")
        self.Label3_36.configure(activeforeground="black")
        self.Label3_36.configure(background="#d9d9d9")
        self.Label3_36.configure(foreground="#000000")
        self.Label3_36.configure(highlightbackground="#d9d9d9")
        self.Label3_36.configure(highlightcolor="black")
        self.Label3_36.configure(text='''Label''')

        self.Label3_37 = tk.Label(self.Labelframe_Node2)
        self.Label3_37.place(relx=0.038, rely=0.436, height=22, width=39
                , bordermode='ignore')
        self.Label3_37.configure(activebackground="#f9f9f9")
        self.Label3_37.configure(activeforeground="black")
        self.Label3_37.configure(background="#d9d9d9")
        self.Label3_37.configure(foreground="#000000")
        self.Label3_37.configure(highlightbackground="#d9d9d9")
        self.Label3_37.configure(highlightcolor="black")
        self.Label3_37.configure(text='''Label''')

        self.Label3_38 = tk.Label(self.Labelframe_Node2)
        self.Label3_38.place(relx=0.038, rely=0.485, height=22, width=39
                , bordermode='ignore')
        self.Label3_38.configure(activebackground="#f9f9f9")
        self.Label3_38.configure(activeforeground="black")
        self.Label3_38.configure(background="#d9d9d9")
        self.Label3_38.configure(foreground="#000000")
        self.Label3_38.configure(highlightbackground="#d9d9d9")
        self.Label3_38.configure(highlightcolor="black")
        self.Label3_38.configure(text='''Label''')

        self.Label3_39 = tk.Label(self.Labelframe_Node2)
        self.Label3_39.place(relx=0.038, rely=0.533, height=22, width=39
                , bordermode='ignore')
        self.Label3_39.configure(activebackground="#f9f9f9")
        self.Label3_39.configure(activeforeground="black")
        self.Label3_39.configure(background="#d9d9d9")
        self.Label3_39.configure(foreground="#000000")
        self.Label3_39.configure(highlightbackground="#d9d9d9")
        self.Label3_39.configure(highlightcolor="black")
        self.Label3_39.configure(text='''Label''')

        self.Label3_40 = tk.Label(self.Labelframe_Node2)
        self.Label3_40.place(relx=0.038, rely=0.582, height=22, width=39
                , bordermode='ignore')
        self.Label3_40.configure(activebackground="#f9f9f9")
        self.Label3_40.configure(activeforeground="black")
        self.Label3_40.configure(background="#d9d9d9")
        self.Label3_40.configure(foreground="#000000")
        self.Label3_40.configure(highlightbackground="#d9d9d9")
        self.Label3_40.configure(highlightcolor="black")
        self.Label3_40.configure(text='''Label''')

        self.Labelframe_Node2_41 = tk.LabelFrame(self.MCT)
        self.Labelframe_Node2_41.place(relx=0.142, rely=0.324, relheight=0.63
                , relwidth=0.296, bordermode='ignore')
        self.Labelframe_Node2_41.configure(relief='groove')
        self.Labelframe_Node2_41.configure(foreground="black")
        self.Labelframe_Node2_41.configure(text='''MCC 1''')
        self.Labelframe_Node2_41.configure(background="#d9d9d9")
        self.Labelframe_Node2_41.configure(highlightbackground="#d9d9d9")
        self.Labelframe_Node2_41.configure(highlightcolor="black")

        self.Label3_42 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_42.place(relx=0.04, rely=0.073, height=22, width=43
                , bordermode='ignore')
        self.Label3_42.configure(activebackground="#f9f9f9")
        self.Label3_42.configure(activeforeground="black")
        self.Label3_42.configure(background="#d9d9d9")
        self.Label3_42.configure(foreground="#000000")
        self.Label3_42.configure(highlightbackground="#d9d9d9")
        self.Label3_42.configure(highlightcolor="black")
        self.Label3_42.configure(justify='left')
        self.Label3_42.configure(text='''Axis 2''')

        self.Label3_31 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_31.place(relx=0.04, rely=0.147, height=22, width=39
                , bordermode='ignore')
        self.Label3_31.configure(activebackground="#f9f9f9")
        self.Label3_31.configure(activeforeground="black")
        self.Label3_31.configure(background="#d9d9d9")
        self.Label3_31.configure(foreground="#000000")
        self.Label3_31.configure(highlightbackground="#d9d9d9")
        self.Label3_31.configure(highlightcolor="black")
        self.Label3_31.configure(text='''Axis 4''')

        self.Label3_32 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_32.place(relx=0.04, rely=0.22, height=22, width=39
                , bordermode='ignore')
        self.Label3_32.configure(activebackground="#f9f9f9")
        self.Label3_32.configure(activeforeground="black")
        self.Label3_32.configure(background="#d9d9d9")
        self.Label3_32.configure(foreground="#000000")
        self.Label3_32.configure(highlightbackground="#d9d9d9")
        self.Label3_32.configure(highlightcolor="black")
        self.Label3_32.configure(text='''Axis 6''')

        self.Label3_33 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_33.place(relx=0.04, rely=0.294, height=22, width=39
                , bordermode='ignore')
        self.Label3_33.configure(activebackground="#f9f9f9")
        self.Label3_33.configure(activeforeground="black")
        self.Label3_33.configure(background="#d9d9d9")
        self.Label3_33.configure(foreground="#000000")
        self.Label3_33.configure(highlightbackground="#d9d9d9")
        self.Label3_33.configure(highlightcolor="black")
        self.Label3_33.configure(text='''Axis 8''')

        self.Label3_34 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_34.place(relx=0.04, rely=0.367, height=22, width=49
                , bordermode='ignore')
        self.Label3_34.configure(activebackground="#f9f9f9")
        self.Label3_34.configure(activeforeground="black")
        self.Label3_34.configure(background="#d9d9d9")
        self.Label3_34.configure(foreground="#000000")
        self.Label3_34.configure(highlightbackground="#d9d9d9")
        self.Label3_34.configure(highlightcolor="black")
        self.Label3_34.configure(justify='left')
        self.Label3_34.configure(text='''Axis 10''')

        self.Label3_35 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_35.place(relx=0.04, rely=0.44, height=22, width=39
                , bordermode='ignore')
        self.Label3_35.configure(activebackground="#f9f9f9")
        self.Label3_35.configure(activeforeground="black")
        self.Label3_35.configure(background="#d9d9d9")
        self.Label3_35.configure(foreground="#000000")
        self.Label3_35.configure(highlightbackground="#d9d9d9")
        self.Label3_35.configure(highlightcolor="black")
        self.Label3_35.configure(text='''Axis 12''')

        self.Label3_36 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_36.place(relx=0.04, rely=0.514, height=22, width=39
                , bordermode='ignore')
        self.Label3_36.configure(activebackground="#f9f9f9")
        self.Label3_36.configure(activeforeground="black")
        self.Label3_36.configure(background="#d9d9d9")
        self.Label3_36.configure(foreground="#000000")
        self.Label3_36.configure(highlightbackground="#d9d9d9")
        self.Label3_36.configure(highlightcolor="black")
        self.Label3_36.configure(text='''Label''')

        self.Label3_37 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_37.place(relx=0.04, rely=0.587, height=22, width=39
                , bordermode='ignore')
        self.Label3_37.configure(activebackground="#f9f9f9")
        self.Label3_37.configure(activeforeground="black")
        self.Label3_37.configure(background="#d9d9d9")
        self.Label3_37.configure(foreground="#000000")
        self.Label3_37.configure(highlightbackground="#d9d9d9")
        self.Label3_37.configure(highlightcolor="black")
        self.Label3_37.configure(text='''Label''')

        self.Label3_38 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_38.place(relx=0.04, rely=0.661, height=22, width=39
                , bordermode='ignore')
        self.Label3_38.configure(activebackground="#f9f9f9")
        self.Label3_38.configure(activeforeground="black")
        self.Label3_38.configure(background="#d9d9d9")
        self.Label3_38.configure(foreground="#000000")
        self.Label3_38.configure(highlightbackground="#d9d9d9")
        self.Label3_38.configure(highlightcolor="black")
        self.Label3_38.configure(text='''Label''')

        self.Label3_39 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_39.place(relx=0.04, rely=0.734, height=22, width=39
                , bordermode='ignore')
        self.Label3_39.configure(activebackground="#f9f9f9")
        self.Label3_39.configure(activeforeground="black")
        self.Label3_39.configure(background="#d9d9d9")
        self.Label3_39.configure(foreground="#000000")
        self.Label3_39.configure(highlightbackground="#d9d9d9")
        self.Label3_39.configure(highlightcolor="black")
        self.Label3_39.configure(text='''Label''')

        self.Label3_40 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_40.place(relx=0.04, rely=0.807, height=22, width=39
                , bordermode='ignore')
        self.Label3_40.configure(activebackground="#f9f9f9")
        self.Label3_40.configure(activeforeground="black")
        self.Label3_40.configure(background="#d9d9d9")
        self.Label3_40.configure(foreground="#000000")
        self.Label3_40.configure(highlightbackground="#d9d9d9")
        self.Label3_40.configure(highlightcolor="black")
        self.Label3_40.configure(text='''Label''')

        self.Label3_41 = tk.Label(self.Labelframe_Node2_41)
        self.Label3_41.place(relx=0.04, rely=0.881, height=22, width=39
                , bordermode='ignore')
        self.Label3_41.configure(activebackground="#f9f9f9")
        self.Label3_41.configure(activeforeground="black")
        self.Label3_41.configure(background="#d9d9d9")
        self.Label3_41.configure(foreground="#000000")
        self.Label3_41.configure(highlightbackground="#d9d9d9")
        self.Label3_41.configure(highlightcolor="black")
        self.Label3_41.configure(text='''Label''')

        self.Labelframe1 = tk.LabelFrame(self.Master_Container)
        self.Labelframe1.place(relx=0.006, rely=0.859, relheight=0.132
                , relwidth=0.985)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Au:Tour''')
        self.Labelframe1.configure(background="#d9d9d9")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





